<?php

/**
 * @file
 *
 * Install basic configurations for Destiny One integration.
 */

/**
 * Implements hook_install().
 */
function unh_d1_drupal_install() {
  variable_set('unh_d1_drupal_program_area', '');
  variable_set('unh_d1_drupal_google_track_enrollments', 0);
  variable_set('unh_d1_drupal_courseSearchBar_blockTitle', UNH_D1_DRUPAL_COURSESEARCHBAR_BLOCKTITLE_DEFAULT);
  variable_set('unh_d1_drupal_courseSearchBar_label', UNH_D1_DRUPAL_COURSESEARCHBAR_LABEL_DEFAULT);
  variable_set('unh_d1_drupal_courseSearchBar_tab', UNH_D1_DRUPAL_COURSESEARCHBAR_TAB_DEFAULT);
  variable_set('unh_d1_drupal_courseSearchBar_phrase', UNH_D1_DRUPAL_COURSESEARCHBAR_PHRASE_DEFAULT);
  variable_set('unh_d1_drupal_courseSearchBar_submit', UNH_D1_DRUPAL_COURSESEARCHBAR_SUBMIT_DEFAULT);
  variable_set('unh_d1_drupal_courseSearchBar_filters', UNH_D1_DRUPAL_COURSESEARCHBAR_FILTERS_DEFAULT);
}

/**
* Implementation of hook_uninstall().
*/
function unh_d1_drupal_uninstall() {
 // Get global variable array
 global $conf;
 foreach (array_keys($conf) as $key) {
   // Find variables that have the module prefix
   if (strpos($key, 'unh_d1_pdt_') === 0) {
     variable_del($key);
   }
 }
}

/**
 * Implements hook_update_N().
 *
 * Setting default variable values.
 */
// function d1client_update_7100() {
//  variable_set('unh_d1_drupal_cache_time', 3600*3);
// }

/**
 * Implements hook_requirements().
 */
function unh_d1_drupal_requirements($phase) {
  if($phase == 'runtime') {

  }
}




